[package]
name = "mumble-prometheus"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libm = "0.2.7"
mumble = { path = "../mumble" }
protobuf = "3.2"

[build-dependencies]
protobuf-codegen = "3.2"
