[package]
name = "mumble"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"

[build-dependencies]
npm_rs = "1.0.0"

[dev-dependencies]
more-asserts = "0.2"
